id: AADD77D32
base_file: fF06C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:01:35.601236
  last_modified_at: 2022-05-31 05:01:35.601242
